#
# Makefile for HDMI sii9022 chip drivers.


sii9022drv-y	+= siHdmiTx_902x_TPI.o
sii9022drv-y	+= hdmi_sii902xA.o

#obj-$(CONFIG_HDMI_Sii902xA) += sii9022drv.o
obj-m += sii9022drv.o

#ccflags-$(CONFIG_I2C_DEBUG_BUS) := -DDEBUG
