cmd_drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.o := aarch64-himix100-linux-gcc -Wp,-MD,drivers/starnet/rtl8821CU/core/mesh/.rtw_mesh_pathtbl.o.d  -nostdinc -isystem /opt/hisi-linux/x86-arm/aarch64-himix100-linux/host_bin/../lib/gcc/aarch64-linux-gnu/6.3.0/include -I./arch/arm64/include -I./arch/arm64/include/generated/uapi -I./arch/arm64/include/generated  -I./include -I./arch/arm64/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mgeneral-regs-only -DCONFIG_AS_LSE=1 -fno-asynchronous-unwind-tables -mpc-relative-literal-loads -fno-delete-null-pointer-checks -Wno-frame-address -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -O1 -Wno-unused-variable -Wno-date-time -Idrivers/starnet/rtl8821CU/include -Idrivers/starnet/rtl8821CU/platform -Idrivers/starnet/rtl8821CU/hal/btc -DCONFIG_MP_INCLUDED -DCONFIG_BT_COEXIST -DCONFIG_EFUSE_CONFIG_FILE -DEFUSE_MAP_PATH=\"/system/etc/wifi/wifi_efuse_8821cu.map\" -DWIFIMAC_PATH=\"/data/wifimac.txt\" -DCONFIG_LOAD_PHY_PARA_FROM_FILE -DREALTEK_CONFIG_PATH=\"/lib/firmware/\" -DCONFIG_TXPWR_BY_RATE=1 -DCONFIG_TXPWR_BY_RATE_EN=1 -DCONFIG_TXPWR_LIMIT=1 -DCONFIG_TXPWR_LIMIT_EN=0 -DCONFIG_RTW_ADAPTIVITY_EN=0 -DCONFIG_RTW_ADAPTIVITY_MODE=0 -DCONFIG_IEEE80211W -DHIGH_ACTIVE_HST2DEV=0 -DCONFIG_BR_EXT '-DCONFIG_BR_EXT_BRNAME="'br0'"' -DCONFIG_RTW_NAPI -DCONFIG_RTW_GRO -DCONFIG_RTW_NETIF_SG -DCONFIG_RTW_DEBUG -DRTW_LOG_LEVEL=4 -DCONFIG_PROC_DEBUG -DCONFIG_RTW_UP_MAPPING_RULE=0 -DDM_ODM_SUPPORT_TYPE=0x04 -DCONFIG_PLATFORM_HISILICON -DCONFIG_PLATFORM_HISILICON_HI3559 -DCONFIG_LITTLE_ENDIAN -DCONFIG_CONCURRENT_MODE -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT -Idrivers/starnet/rtl8821CU/hal/phydm -DCONFIG_RTL8821C    -DKBUILD_BASENAME='"rtw_mesh_pathtbl"'  -DKBUILD_MODNAME='"8821cu"' -c -o drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.o drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.c

source_drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.o := drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.c

deps_drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.o := \
    $(wildcard include/config/rtw/mesh.h) \
    $(wildcard include/config/rtw/mesh/cto/mgate/carrier.h) \

drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.o: $(deps_drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.o)

$(deps_drivers/starnet/rtl8821CU/core/mesh/rtw_mesh_pathtbl.o):
